# Install command-line tools using Homebrew


################################################
##                    TAPS                    ##
################################################

tap "raggi/ale"
tap "jlhonora/lsusb"
tap "homebrew/dupes"
tap "homebrew/fuse"
tap "homebrew/apache"
tap "homebrew/core"
tap "homebrew/php"
tap "homebrew/versions"
tap "homebrew/binary"
tap "homebrew/boneyard"
tap "homebrew/python"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap 'caskroom/cask'


################################################
##                    CASKS                   ##
################################################
# Configure where our applications go
cask_args appdir: '/Applications'
# get brew cask for apps
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "sublime-text"
cask "atom"
cask "filezilla"
cask "firefox"
cask "iterm2"
cask "mysqlworkbench"
cask "paw"
cask "sourcetree"
cask "spotify"
cask "transmission"
cask "vlc"
cask "little-snitch"
cask "adium"
cask "arduino"
cask "clion"
cask "colorsnapper"
cask "db-browser-for-sqlite"
cask "evernote"
cask "slack-beta"
cask "hex-fiend"
cask "angry-ip-scanner"
cask "openscad"
cask "videostream"
cask "sdformatter"
cask "sizeup"
cask "vnc-viewer"
cask "unetbootin"
cask "kaleidoscope"
cask "java"


################################################
##                 Brew Stuff                 ##
################################################

brew "coreutils"
brew "binutils"
brew "autoconf"
brew "automake"
brew "ack"
brew "batik"
brew "bfg"
brew "boost"
brew "brew-gem"
brew "brew-pip"
brew "cairo"
brew "cloog"
brew "cmake"
brew "colordiff"
brew "curl", args: ["with-openssl"]
brew "czmq"
brew "dbus"
brew "ed", args: ["default-names"]
brew "e2fsprogs"
brew "exiftool"
brew "faac"
brew "fdk-aac"
brew "fdupes"
brew "ffmpeg", args: ["HEAD", "with-fdk-aac", "with-fontconfig", "with-freetype", "with-libvorbis", "with-openh264", "with-tools"]
brew "findutils", args: ["default-names"]
brew "freexl"
brew "fswatch"
brew "gawk"
brew "ghostscript"
brew "git", args: ["with-curl","with-openssl"]
brew "glibmm"
brew "gnu-getopt"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar", args: ["with-default-names"]
brew "gnu-which", args: ["with-default-names"]
brew "gnupg"
brew "gperf"
brew "graphicsmagick"
brew "graphviz"
brew "grc"
brew "grep", args: ["with-default-names"]
brew "gtk+"
brew "hardlink"
brew "help2man"
brew "hicolor-icon-theme"
brew "hoedown"
brew "htop"
brew "httpd", restart_service: true
brew "httpie"
brew "httrack"
brew "imagemagick"
brew "isl@0.11"
brew "jhead"
brew "jpegoptim"
brew "json-c"
brew "lame"
brew "lbzip2"
brew "less"
brew "libao"
brew "libav"
brew "libffi"
brew "libidn"
brew "libksba"
brew "liblwgeom"
brew "libmpc@0.8"
brew "libogg"
brew "libotr"
brew "libsigc++"
brew "libsodium"
brew "libspatialite"
brew "libssh2"
brew "libsvg"
brew "libtool"
brew "libusb-compat"
brew "libvo-aacenc"
brew "libvorbis"
brew "libxml++"
brew "libyaml"
brew "lighttpd"
brew "lua"
brew "lzlib"
brew "mas"
brew "mcrypt"
brew "media-info"
brew "mhash"
brew "moreutils"
brew "mp3info"
brew "netcat"
brew "nettle"
brew "ngrep"
brew "nmap"
brew "numpy"
brew "openh264"
brew "p7zip"
brew "pandoc"
brew "perl"
brew "pngcrush"
brew "progress"
brew "proj"
brew "protobuf"
brew "pv"
brew "pyenv"
brew "qcachegrind"
brew "qt"
brew "re2c"
brew "rename"
brew "ripgrep"
brew "rmtrash"
brew "ruby"
brew "sassc"
brew "screen"
brew "selenium-server-standalone"
brew "sip"
brew "sqlite"
brew "ssdeep"
brew "ssh-copy-id"
brew "tree"
brew "ttfautohint"
brew "unixodbc"
brew "unrar"
brew "utf8proc"
# brew "vim", args: ["with-override-system-vi"]
brew "vimpager"
brew "vorbis-tools"
brew "webkit2png"
brew "wget"
brew "xvid"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "homebrew/php/composer"
brew "homebrew/php/php71", args: ["with-homebrew-curl", "with-httpd"]
brew "homebrew/php/wp-cli"
brew "jlhonora/lsusb/lsusb"
brew "raggi/ale/openssl-osx-ca"
