# Install command-line tools using Homebrew
# `brew tap homebrew/bundle`
# `brew bundle`
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
#update
# Upgrade any already-installed formulae
#upgrade
tap "homebrew/versions"
tap "homebrew/dupes"
tap "homebrew/binary"
tap "josegonzalez/homebrew-php"
tap "homebrew/boneyard"
tap "homebrew/php"
tap "homebrew/python"

tap "caskroom/versions"

# cask install "dropbox"
# cask install "google-chrome"
# cask install "iterm2"
# cask install "sublime-text"
# cask install "atom"
cask install "filezilla"
cask install "firefox"
# cask install "iterm2"
cask install "mysqlworkbench"
cask install "paw"
# cask install "sourcetree"
cask install "spotify"
cask install "transmission"
cask install "vlc"
cask install "little-snitch"
cask install "adium"
cask install "arduino"
cask install "clion"
cask install "colorsnapper"
cask install "db-browser-for-sqlite"
cask install "evernote"
cask install "slack-beta"
cask install "hex-fiend"
cask install "angry-ip-scanner"
cask install "openscad"
cask install "videostream"
cask install "sdformatter"
cask install "sizeup"
cask install "vnc-viewer"
cask install "unetbootin"
cask install "kaleidoscope"


# brew "ack"
# brew "android-platform-tools"
# brew "ant"
# brew "batik"
# brew "berkeley-db4"
# brew "bfg"
# brew "binutils"
# brew "binwalk"
# brew "homebrew/versions/bison27"
# brew "boost"
# brew "brew-gem"
# brew "brew-pip"
# brew "homebrew/boneyard/class-dump"
# brew "cloog"
# brew "colordiff"
# brew "coreutils"
# brew "curl"
# brew "dbus"
# brew "e2fsprogs"
# brew "exiftool"
# brew "ffmpeg"
# brew "findutils"
# brew "flex"
# brew "flow"
# brew "fontforge"
# brew "gcc"
# brew "homebrew/versions/gcc48"
# brew "gdal"
# brew "ghi"
# brew "ghostscript"
# brew "gifsicle"
# brew "git"
# brew "git-flow"
# brew "gnu-sed"
# brew "gnupg"
# brew "gnutls"
# brew "graphicsmagick"
# brew "graphviz"
# brew "grc"
# brew "homebrew/dupes/grep"
# brew "gtk+"
# brew "hardlink"
# brew "hoedown"
# brew "htop-osx"
# brew "httrack"
# brew "jhead"
# brew "jpegoptim"
# brew "lbzip2"
# brew "homebrew/dupes/less"
# brew "libav"
# brew "libidn"
# brew "libksba"
# brew "libotr"
# brew "homebrew/binary/libspotify"
# brew "libssh2"
# brew "libsvg"
# brew "libusb-compat"
# brew "libvo-aacenc"
# brew "libxml++"
# brew "lighttpd"
# brew "jlhonora/lsusb/lsusb"
# brew "lua"
# brew "media-info"
# brew "moreutils"
# brew "mp3info"
# brew "mysql"
# brew "netcat"
# brew "ngrep"
# brew "nmap"
# brew "homebrew/python/numpy"
# brew "pandoc"
# brew "perl"
# brew "phantomjs"
# brew "homebrew/php/php56-imagick"
# brew "homebrew/php/php56-intl"
# brew "homebrew/php/php56-mcrypt"
# brew "homebrew/php/php56-xdebug"
# brew "pngcrush"
# brew "pyenv"
# brew "homebrew/boneyard/pyside"
# brew "python"
# brew "python3"
# brew "qcachegrind"
# brew "re2c"
# brew "rename"
# brew "rmtrash"
# brew "ruby"
# brew "s3cmd"
# brew "sassc"
# brew "homebrew/dupes/screen"
# brew "selenium-server-standalone"
# brew "slimerjs"
# brew "ssh-copy-id"
# brew "swftools"
# brew "the_platinum_searcher"
# brew "the_silver_searcher"
# brew "thefuck"
# brew "tmux"
# brew "tree"
# brew "ttf2eot"
# brew "ttfautohint"
# brew "unrar"
# brew "vim"
# brew "vimpager"
# brew "vorbis-tools"
# brew "webkit2png"
# brew "wget"
# brew "homebrew/php/wp-cli"
# brew "yarn"
# brew "homebrew/dupes/zlib"
# brew "zsh"

# Remove outdated versions from the cellar
#cleanup
