#!/usr/bin/env bash

REMOTEHOST="myagent.site"
REMOTEPATH="/var/www/staging.myagent.site/"
LOCALPATH="/var/www/myagent.site/"
SYNCFROM=false
SPECIFICDIRECTORY=false

BGreen='\x1b[1;32m'
Cyan='\x1b[0;36m'
Yellow='\x1b[0;33m'
BYellow='\x1b[1;33m'
NC="\x1b[m"

EXCLUDES=(
  "backup*"
  "testing12345"
  "tests*"
  "testing"
  "vendor*"
  "predis"
  "bandwidthd"
  "docs"
  "cache*"
  ".idea"
  ".svn"
  "*.zip"
  "tmp/*"
  ".git"
  "content/uploads"
  "node_modules"
  "screenshots/*.png"
)

OPTIONS=(
  "checksum"
  "compress"
  "delete"
  "group"
  "human-readable"
  "links"
  "owner"
  "perms"
  "progress"
  "recursive"
  "recursive"
  "safe-links"
  "stats"
  "times"
  "update"
)

DOIT=false

for x in "${EXCLUDES[@]}"; do
 EXCLUDES_TOTAL="${EXCLUDES_TOTAL} --exclude=${x}"
done

for x in "${OPTIONS[@]}"; do
 OPTIONS_TOTAL="${OPTIONS_TOTAL} --${x}"
done


function usage() {
    echo -e "Synchronizes ${Cyan}${REMOTEHOST}${BCyan}${REMOTEPATH}${White} → ${Yellow}local${BYellow}${LOCALPATH}${NC}"
    echo -e ""
    echo -e "${BGreen}$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")${NC}"
    echo -e "\t-h --help"
    echo -e "\t-d --directory <specific directory>"
    echo -e "\t--db-path=$DB_PATH"
    echo -e "\t--<option name> Add an additional option$DB_PATH"
    echo -e ""
}

while [ "$1" != "" ]; do
    key="${1}"
    case ${key} in
        -h | --help)
            usage
            exit
            ;;
        -d | --directory)
            SPECIFICDIRECTORY="${2}"
            shift
            ;;
        --db-path)
            DB_PATH="${2}"
            shift
            ;;
        --doit)
            DOIT=true
            # shift
            ;;
        --from)
            SYNCFROM=true
            # shift
            ;;
        *)
            OPTIONS_TOTAL="${OPTIONS_TOTAL} ${1}"
            ;;
    esac
    shift
done

if [ $SPECIFICDIRECTORY != false ]; then
  REMOTEPATH+="${SPECIFICDIRECTORY}/"
  LOCALPATH+="${SPECIFICDIRECTORY}/"
fi


rcommand="rsync"
rcommand+=" $EXCLUDES_TOTAL"
rcommand+=" $OPTIONS_TOTAL"

if [ $SYNCFROM = true ]; then
  SYNCTEXT="${Cyan}${REMOTEHOST}${BCyan}${REMOTEPATH}${White} → ${Yellow}local${BYellow}${LOCALPATH}"
  rcommand+=" eboney@${REMOTEHOST}:${REMOTEPATH} ${LOCALPATH}"
else
  SYNCTEXT="${Yellow}local${BYellow}${LOCALPATH} ${White}→ ${Cyan}${REMOTEHOST}${BCyan}${REMOTEPATH}"
  rcommand+=" ${LOCALPATH} eboney@${REMOTEHOST}:${REMOTEPATH}"
fi

if [ $DOIT = false ]; then
  rcommand+=" --dry-run"
  echo -e ""
  echo -e "${White}Doing a ${BGreen}DRY RUN${White} of ${SYNCTEXT}${NC}"
  echo -e ""
  # echo $rcommand
  eval $rcommand
  echo -e ""
  echo -e "${White}That was a ${BGreen}DRY RUN${White} of ${SYNCTEXT}${NC}, add ${BRed}--doit${White} to do a REAL run${NC}"
  echo -e ""
else
  echo -e ""
  echo -e "${White}Doing a ${BRed}LIVE RUN${White} of ${SYNCTEXT}${NC}"
  echo -e ""
  # echo $rcommand
  eval $rcommand
  echo -e ""
  echo -e "${White}That was a ${BRed}REAL RUN${White} of ${SYNCTEXT}${NC}"
  echo -e ""
fi