#!/usr/bin/env bash
ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

if [[ -z "$1" ]]; then
  echo -e "\n\t${BCyan} Useage: ${White}${ME} ${Yellow}<ip> ${Red}<host>${NC}\n"
else
  sudo sh -c 'echo "'"${1}"'\t'"${2}"'" >> /etc/hosts'
fi