#!/bin/bash

VERSION=0.4

REDON=$BRed
GREENON=$BGreen
COLOROFF=$NC

IOS=false
ANDROID=false

LANDSCAPE=false
RETINA=false

OUTPUT="screenshot"

ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"


checkRequirements() {
    if ! hash webkit2png &> /dev/null; then
        echo -e "${REDON}webkit2png was not found.${NC}\nPlease install to continue. http://www.paulhammond.org/webkit2png/\n"
        echo -e "Or \`brew install webkit2png\`"
        exit
    fi
}

displayVersion() {
    echo "${ME} $VERSION"
}

displayHelp() {

    echo -e "\n    ${DarkGray}Usage:${NC} ${BPurple}${ME} ${LightGray}[options]${NC} ${Cyan}[http://localhost/]${NC}\n\n"

    echo -e "    OPTIONS:"
    echo -e "       -v, --version             show the version number and then exit"
    echo -e "       -h, --help                show this help message and then exit"
    echo -e "    "
    echo -e "       -i, --ios                 create iOS device sizes"
    echo -e "       -a, --android             create Android device sizes"
    echo -e "    "
    echo -e "       -l, --landscape           create landscape versions"
    echo -e "       -r, --retina              create retina versions"
    echo -e "    "
    echo -e "       -o=name, --output=name    change name of saved files"
    echo -e "\n\n"

}

parseOptions() {

    local args=(${@// /})

    for arg in "${args[@]}"; do

        case $arg in

            -v | --version ) displayVersion; exit;;
            -h | --help ) displayHelp; exit;;

            -i | --ios ) IOS=true;;
            -a | --android ) ANDROID=true;;

            -l | --landscape ) LANDSCAPE=true;;
            -r | --retina ) RETINA=true;;

            -o=* | --output=* ) OUTPUT=$(echo "$arg" | sed -e 's/-o=//' -e "s/--output=//");;

            http* ) URL=$arg;;

            ?* ) echo "Invalid option $arg"; displayHelp; exit;;

        esac

    done

}

saveScreenshot() {

    SITENAME=$(echo ${URL} | sed 's/https:\/\///g' | sed 's/http:\/\///g' | sed 's/\///g' | sed 's/www\.//g')

    webkit2png --scale=1 --width "$1" --height "$2" --fullsize -o "${SITENAME}-$3" "$URL" &> /dev/null

    printf "Saved ${REDON}%s${COLOROFF} screenshot to ${REDON}%s${COLOROFF}\n" "$3" "${SITENAME}"-"$3"

    if $RETINA; then

        webkit2png --scale=1 --zoom 2.0 --width "$1" --height "$2" --fullsize -o "${SITENAME}-$3-@2x" "$URL" &> /dev/null

        printf "Saved ${REDON}%s${COLOROFF} (@2x) screenshot to ${REDON}%s${COLOROFF}\n" "$3" "${SITENAME}"-"$3"-@2x

    fi

}

checkRequirements

parseOptions "$@"

if [ "$URL" ]; then

    if $IOS; then

        saveScreenshot "667" "375" "iPhone6-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "667" "375" "iPhone6-Landscape"
        fi

        saveScreenshot "414" "736" "iPhone6Plus-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "414" "736" "iPhone6Plus-Landscape"
        fi

        saveScreenshot "320" "568" "iPhone5-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "568" "320" "iPhone5-Landscape"
        fi

        saveScreenshot "768" "1024" "iPad-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "1024" "768" "iPad-Landscape"
        fi

    fi

    if $ANDROID; then

        saveScreenshot "360" "640" "Nexus5-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "360" "640" "Nexus5-Landscape"
        fi

        saveScreenshot "600" "960" "Nexus7-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "960" "600" "Nexus7-Landscape"
        fi

        saveScreenshot "800" "1280" "Nexus10-Portrait"

        if $LANDSCAPE; then
            saveScreenshot "1280" "800" "Nexus10-Landscape"
        fi

    fi

    saveScreenshot "1440" "740" "Desktop"

    echo -e "Completed at ${GREENON}$(date +"%m-%d-%Y %r")${COLOROFF}"

else

    displayHelp

fi
