#!/usr/bin/env bash
#
# "/var/www/beta.thepaperlessagent.com/" "/var/www/dashboard.thepaperlessagent.com/" "/var/www/paperlessagent/" "/var/www/red.marketing/" "/var/www/myagent.site/"
webdirs=(  "/var/www/beta.thepaperlessagent.com/" "/var/www/dashboard.thepaperlessagent.com/" "/var/www/paperlessagent/" "/var/www/red.marketing/" "/var/www/myagent.site/")

for i in "${webdirs[@]}"
do
   echo -e "${BWhite}Syncing ${BCyan}${i}${BWhite}...${NC}"
   rsync -avz --progress --delete --prune-empty-dirs --links --exclude=".git*"  --exclude="node_modules*"  --exclude="tests*" --exclude="testing*" --exclude="uploads*" --exclude="wp-includes*" --exclude="*.sql" --exclude="wp-admin*" ${i} eboney@192.168.0.100:${i}
done