alias nh='cd ~/Code/Clients/NuHabitat/'
alias exp='cd ~/Code/Clients/NuHabitat/experience.nH'
alias site='cd /var/www/Site'
alias prod='changetitle production.agentvow.com && ssh prod'
alias ell='changetitle elliot.agentvow.com && ssh elliot.agentvow.com'
alias media='changetitle media.agentvow.com && ssh media'
